version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
  
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set main http://minio:9000 minio minio123;
      /usr/bin/mc mb main/main;
      /usr/bin/mc policy set public main/main;
      exit 0;
      "
  
  postgres_fds_pipeline:
    container_name: postgres_fds_pipeline
    image: fds-postgres
    build: ./postgres/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=dagster
      - APP_DB_PASS=dagster
      - APP_DB_NAME=main
    ports:
      - 5436:5432
    # wait till all scripts are done etc.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  minio_storage: {}