FROM python:3.10
RUN mkdir /app
COPY ./ /app
COPY pyproject.toml /app
WORKDIR /app
ENV PYTHONPATH=${PYTHONPATH}:${PWD} 
RUN pip3 install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --only main

# Run dagster gRPC server on port 4000

EXPOSE 4000

CMD ["poetry", "run", "dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "--package-name", "fds_pipeline"]